version: '3.8'

services:
  backend:
    image: vinanamira/alitnest-be:latest
    container_name: alitnest-be
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/alitnest
    networks:
      - alitnet

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - alitnet

volumes:
  mongo-data:

networks:
  alitnet: