version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - alitnest-net

  alitnest-be:
    build: .
    container_name: alitnest-be
    ports:
      - "3000:80"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://127.0.0.1:27017/alitnest?directConnection=true
    networks:
      - alitnest-net

volumes:
  mongodb_data:

networks:
  alitnest-net:
    driver: bridge