version: '3.8'

services:
  backend:
    build: .
    container_name: alitnest-be
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - alitnet

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - alitnet

networks:
  alitnet:
    driver: bridge

volumes:
  mongo_data: