version: '3'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - alitnest-net

  alitnest-be:
    build: .
    container_name: alitnest-be
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/alitnest
    depends_on:
      - mongodb
    networks:
      - alitnest-net

volumes:
  mongodb_data:

networks:
  alitnest-net:
    driver: bridge