version: '3'
services:
  alitnest-be:
    container_name: alitnest-be
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - PORT=80
      - MONGO_URL=mongodb://mongodb:27017/alitnest
    depends_on:
      - mongodb
    networks:
      - alitnest-net

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - alitnest-net

volumes:
  mongodb_data:

networks:
  alitnest-net:
    driver: bridge