version: '3.8'
services:
  backend:
    image: vinanamira/alitnest-be:latest
    container_name: alitnest-be
    ports:
      - "27018:27017"
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: